id: 6c2991debc97457c83b5e5ad6cbe3895
initial_creation_type: ocr
source_metadata:
  volumes:
    d99ef8c2228d4076ac6f7e9bfc1bd3f5:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ''
      total_pages: 1498
      volume_number: 65
